version: 2

sphinx:
  configuration: docs_cn/conf.py

build:
  image: testing

# NOTE: only build default HTML
# formats: all

python:
  version: 3.9
  install:
    - requirements: docs_cn/requirements.txt
    - method: pip
      path: .